proxy:
  address: "localhost:9011"
  domain: "localhost"
  allowInsecureAuth: true
  serverCrt: "/path/to/directory/contains/cert/server.crt"
  serverKey: "/path/to/directory/contains/cert/server.key"
  readTimeout: 10
  writeTimeout: 10
  maxMessageBytes: 1024 * 1024
  maxRecipients: 50
  retryAttempts: 5
  retryDelay: 2
smtp:
  address: "smtp.example.com:465"
  username: "fakeuser"
  password: "fakepassword"
